env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - airbnb-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
rules: {
  "no-param-reassign": [2, {"props": false}]
}
settings: {
  "import/resolver": {
    "jest": {
      "jestConfigFile": "./jest.config.js"
    }
  }
}
